[formatter.justfile]
command = "/nix/store/fkzwwgx9xgabzlrgyhqndq5bxzsj3vk6-just-1.36.0/bin/just"
excludes = []
includes = ["justfile"]
options = ["--unstable", "--fmt", "--check", "--justfile"]

[formatter.mdformat]
command = "/nix/store/lhp1bzj7k6kjkxcsspfld6bcfn0wavjb-python3.12-mdformat-0.7.18/bin/mdformat"
excludes = []
includes = ["*.md"]
options = []

[formatter.nixfmt]
command = "/nix/store/xcf7zgim2d37d787f7mymlg4ca66z6kz-nixfmt-unstable-2024-08-16/bin/nixfmt"
excludes = []
includes = ["*.nix"]
options = []

[formatter.yamlfmt]
command = "/nix/store/fv1vhhp2zg5jqmn2pyn370js84jl7f3q-yamlfmt-0.13.0/bin/yamlfmt"
excludes = []
includes = ["*.yaml", "*.yml"]
options = []

[global]
excludes = ["*.lock", "*.patch", "package-lock.json", "go.mod", "go.sum", ".gitignore", ".gitmodules", ".hgignore", ".svnignore", "./.direnv", ".envrc", "treefmt.toml"]
